#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative './agent'

# Create and run the CLI
cli = InteractiveCLI.new
begin
  cli.run
rescue Interrupt
  puts "\nInterrupted by user. Exiting..."
end
